name: emcid
channels:
  - pytorch
  - defaults
dependencies:
  - python==3.10.12
  - cudatoolkit=11.8.0
  - pip=23.1.2
  - pip:
      - accelerate==0.23.0
      - datasets==2.14.5
      - diffusers==0.25.1
      - einops==0.3.0
      - huggingface-hub
      - imageio==2.9.0
      - lpips==0.1.4
      - matplotlib==3.6.3
      - nudenet==3.0.1
      - numpy==1.23.3
      - open-clip-torch==2.20.0
      - opencv-python
      - pandas==1.5.1
      - pillow==10.0.1
      - pytorch-fid==0.3.0
      - scipy==1.11.2
      - timm==0.9.7
      - tokenizers==0.13.3
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.64.1
      - transformers==4.27.4
      - seaborn
      - NudeNet
